config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :articles do
    resources :reactions, only: :create
  end
  
  root to: "articles#index"
  
  
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :reactions

    validates :introduction, presence: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
    belongs_to :article
    belongs_to :user

    enum status: { like: 0, dislike: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :move_to_index, except: [:index]

    def index
        @article = Article.all
    end

    def new
         @article = Article.new
    end

    def create
        @article = Article.create(article_params)
        if @article.save
            redirect_to action: :index
        else
            redirect_to action: :new
        end
    end

    def show
        @articles = Article.find(:id)
    end

    private
    def move_to_index
        unless user_signed_in?
          redirect_to action: :index
        end
    end

    def article_params
        params.require(:article).permit(:name,:protein,:fat,:carbo,:introduction,:image).merge(user_id: current_user.id)
    end

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!

    def create
        @reaction = Reaction.new(status: params[:reaction], user_id: current_user.id, article_id: params[:article_id])
        if  @reaction.save!
            redirect_to  articles_path
        else
            redirect_to  articles_path
        end
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @myarticle = Article.includes(:user)
        @name = current_user&.name
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_newedit.html.erb
 <div class="container">
    <div class="form_content">
    <%= form_with model: article, local: true do |f| %>
      <h3>投稿する</h3>
      <div class="input_form">
       <%= f.file_field :image, class: "form_image", placeholder: "画像" %>
       <%= f.text_field :protein, class: "form_nutri",placeholder: "タンパク質" %>
       <%= f.text_field :fat, class: "form_nutri", placeholder: "脂質" %>
       <%= f.text_field :carbo,  class: "form_nutri",placeholder: "炭水化物" %>
       <%= f.text_area :introduction, class: "form_introf", form_placeholder: "説明", rows: "5" %>
       <%= f.submit "SEND" %>
    <% end %>
    </div>
  </div>

app/views/articles/index.html.erb
<div class="loginPage">
  <div class="container">
    <header>
    <div class="header_list">
        <div class="header_lists">
            <div><%= link_to new_article_path, class: "food_list" do %>
            <i class="fas fa-utensils fa-3x"></i>
            <% end %></div>
            <div><%= link_to users_path, class: "user_list" do%>
            <i class="fas fa-user fa-3x"></i></div>
            <%end%>
        </div>
    
    <div>
    </header>

  <% if user_signed_in?%>
   <div id="tinderslide">
      <ul>
        <% @article.each do |article| %>
            <li data-article_id="<%= article.id %>">
              <%= image_tag article.image %>
              <div class="like"></div>
              <div class="dislike"></div>
            </li>
        <% end %>
      </ul>
      <div class="noUser">新規投稿がありません。</div>
    </div>
  </div>
  <script>
  // スワイプするユーザー数の定数を定義
  var articleNum = "<%= @article.length %>"
  var currentIndex = 0;
  
  var postReaction = function (article_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "/articles/" + article_id + "/reactions",
      data: {
        reaction: reaction,
        article_id: article_id
      },
      success: function(j_data){
        console.log(j_data)
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentIndex++;
      checkarticleNum();
      var article_id = item[0].dataset.article_id
      postReaction(article_id, 'dislike')
    },
    onLike: function (item) {
      currentIndex++;
      checkarticleNum();
      var article_id = item[0].dataset.article_id
      postReaction(article_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });
  function checkarticleNum() {
    // スワイプするユーザー数とスワイプした回数が同じになればaddClassする
    if (currentIndex === articleNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>
             <div class="navi_btn">
                <div class="btn loginPage_contents_btn">←見送り</div> 
                <div class="btn loginPage_contents_btn">キープ→</div>
            </div> 
        <%else%> 
            <div class="navi_btn">
               <%= link_to "新規登録", new_user_registration_path, class: "btn loginPage_contents_btn" %>
               <%= link_to "ログイン", new_user_session_path, class: "btn loginPage_contents_btn" %>
            </div>
      <%end%>
    </div>
     <footer>
      <p align="center">
        Copyright ketokeep 2020.
      </p>
    </footer>
  </div>
</div>

app/views/articles/new.html.erb
<div class="contents">
  <%= render partial: 'newedit.html.erb', locals: { article: @article } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keto28283</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
   
  </body>
</html>

app/views/users/index.html.erb
 <div class="mycontent"> 
    <div class="mycontens">
      <p>投稿一覧ページ</p>
        <% @myarticle.each do |article| %>
        <div class="content_post">
          <%= image_tag article.image%>
        </div>
        <% end %>
    </div>
</div>